"""Reporting utilities for generating HTML reports with Plotly visualizations."""

from seedlearn.reporting.pipeline_html import generate_pipeline_report
from seedlearn.reporting.html import (
    build_confusion_matrix,
    build_label_support_chart,
    build_per_label_metrics,
    build_summary_table,
    build_support_set_distribution,
    build_support_vs_performance,
    build_top_errors,
    generate_key_findings,
    get_chart_interpretation,
    get_conclusions_section,
    get_evaluation_context,
    get_html_footer,
    get_html_header,
    get_support_set_section,
    interpret_accuracy,
    interpret_confusion_patterns,
    interpret_per_class_performance,
    interpret_support_vs_performance,
    interpret_top5_accuracy,
    wrap_plotly_div,
)

__all__ = [
    "generate_pipeline_report",
    "build_confusion_matrix",
    "build_label_support_chart",
    "build_per_label_metrics",
    "build_summary_table",
    "build_support_set_distribution",
    "build_support_vs_performance",
    "build_top_errors",
    "generate_key_findings",
    "get_chart_interpretation",
    "get_conclusions_section",
    "get_evaluation_context",
    "get_html_footer",
    "get_html_header",
    "get_support_set_section",
    "interpret_accuracy",
    "interpret_confusion_patterns",
    "interpret_per_class_performance",
    "interpret_support_vs_performance",
    "interpret_top5_accuracy",
    "wrap_plotly_div",
]
